In [1]:
import numpy as np
from IPython.display import clear_output
from time import sleep

def create(chance, N):
    ocean = np.random.choice(a = [0,1,2,3], size = (N,N), p = list(chance))
    return ocean

def get_neigh(x, y, ocean, N):
    fish_count = 0
    shrimp_count = 0
    for i in range(-1,2):
        for j in range(-1,2):
            k = x+i
            l = y+j
            if k < 0 or l < 0 or k >= N or l >= N or (k==x and l == y):
                continue
            if ocean[k,l] == 2:
                fish_count+=1
            if ocean[k,l] == 3:
                shrimp_count+=1
    return [fish_count, shrimp_count]
    
def next_step(ocean, prot_ocean, N):
    for i in range(N):
        for j in range(N):
            a = get_neigh(i,j,prot_ocean,N)
            if prot_ocean[i, j] == 0:
                if a[0] == 3:
                    ocean[i, j] = 2
                elif a[1] == 3:
                    ocean[i, j] = 3
            if prot_ocean[i, j] == 2:
                if a[0] > 3 or a[0] < 2:
                    ocean[i, j] = 0
            if prot_ocean[i, j] == 3:
                if a[1] > 3 or a[1] < 2:
                    ocean[i, j] = 0
    return ocean
            
                       
if __name__ == '__main__':
    chance = (0.21, 0.15, 0.32, 0.32)
    N = 25
    ocean = create(chance, N)
    print(ocean, end = '\n')
    
    while True:
        sleep(2)
        clear_output(wait=True)
        prot_ocean = np.copy(ocean)
        print(next_step(ocean, prot_ocean, N), end = '\n')
        if np.array_equal(prot_ocean, ocean):
            print("Life in ocean was died!")
            break

[[0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0]
 [1 0 0 1 0 0 0 0 0 2 2 0 0 0 0 1 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0 0 2 2 1 0 1 0 0 0 0 0 0 0 0 3 3 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 3 0 3 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 3 3 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0]
 [0 2 2 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 2 2 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 3 3 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 3 3 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 1 1 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0]
 [0 3 3 1 0 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0]
 [0 3 0 0 3 0 0 0 0 0 0 0 1 3 3 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 3 3 0 0 1 1 0 0 0 0 3 3 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [2 1 0 1 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 